# MacOS:   built with Flutter 3.19.4 (Intel x64), CocoaPods 1.15.2
# Windows: built with Flutter 3.19.4
name: tommynotes
description: "Domingo Virtual Notes"
publish_to: 'none'
version: 24.11.26+8

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 6.1.1               # open-file dialog
  sqflite: 2.3.2                   # DB support
  sqflite_common_ffi: 2.3.2        # FFI support: https://stackoverflow.com/questions/76158800
  markdown_widget: 2.3.2+3         # markdown widget
  shared_preferences: 2.2.2        # key-value storage
  flutter_platform_alert: 0.5.1    # simple native platform dialogs
  native_context_menu: 0.2.2+5     # context menu
  package_info_plus: 6.0.0         # get version, build and app name
  window_manager: 0.3.8            # set title to window
  path: 1.9.0                      # get basename from a filename

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
